### ISSUE TITLE
Original BL-Touch not working on nano V1.2

### ISSUE THREAD

**Issue by olaf-h** [makerbase-mks/MKS-Robin-Nano-Firmware#5] opened 2020-04-07 09:10 UTC
I try to connect a BL-Touch 3,1 to the supplied ports on the nano board either as a z-Limit switch or only for bed leveling on z-max (MKS Firmware 2.0.1). The sensor is not working in any configuration (with marlin firmware it's running) When I switch to a BL-Touch Clone (Touch 3d) it's working properly with the original MKS Firmware. Is there any configuration I need to adjust or is there simply an HW issue or a bug in the original MKS Firmware

**Comment by makerbase-mks** [comment] 2020-04-07 11:09
Hi! Nano firmware is compatible with hardware prior to BLTOUCH V3.1, but BLTOUCH V3.1 modifies the hardware so that existing firmware cannot drive it. Subsequent firmware versions, we are compatible with BLTOUCH V3.1

**Comment by JinwooJang** [comment] 2020-04-11 01:24
Dear makerbase
could you let me know plan to release next version ?

the reason not working BLTOUCH V3.1 is this PWM duty cycle ?
as I see, out of range PWM output which is required by BLTOUCH v3.1.


> 
> 
> Hi! Nano firmware is compatible with hardware prior to BLTOUCH V3.1, but BLTOUCH V3.1 modifies the hardware so that existing firmware cannot drive it. Subsequent firmware versions, we are compatible with BLTOUCH V3.1

**Comment by makerbase-mks** [comment] 2020-04-11 02:04
It is caused by different pulse widths. We will deal with this problem in these two days.

**Comment by olaf-h** [comment] 2020-04-15 05:46
Great, thnx. With Marlin it’s working properly, but I like the original MKS software :)

**Comment by makerbase-mks** [comment] 2020-08-26 11:27
@olaf-h 
I will close this question temporarily.

**Closed as completed by makerbase-mks** 2020-08-26 11:27 UTC
